"""release

Revision ID: 117e9f4f2620
Revises: 6095e79ac200
Create Date: 2025-12-16 21:50:58.043746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '117e9f4f2620'
down_revision: Union[str, Sequence[str], None] = '6095e79ac200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_information', sa.String(length=50), nullable=False),
    sa.Column('method', postgresql.ENUM('WHAPSAPP', 'EMAIL', name='receiptmethod', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('theme', sa.String(length=700), nullable=True),
    sa.Column('text_for_send', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_password', sa.String(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_profile_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=True)
    op.create_table('contractor_date_link',
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('last_sent', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], ),
    sa.PrimaryKeyConstraint('contractor_id', 'date_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractor_date_link')
    op.drop_index(op.f('ix_profile_email'), table_name='profile')
    op.drop_table('profile')
    op.drop_table('dates')
    op.drop_table('contractors')
    # ### end Alembic commands ###
