"""without_method

Revision ID: 315e7b1a24dc
Revises: e1f3c110fac5
Create Date: 2025-12-17 16:00:28.813231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '315e7b1a24dc'
down_revision: Union[str, Sequence[str], None] = 'e1f3c110fac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'method')
    sa.Enum('WHAPSAPP', 'EMAIL', name='receiptmethod').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WHAPSAPP', 'EMAIL', name='receiptmethod').create(op.get_bind())
    op.add_column('contractors', sa.Column('method', postgresql.ENUM('WHAPSAPP', 'EMAIL', name='receiptmethod', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
