"""add_logs

Revision ID: 56f0cac094b6
Revises: 79275844a9ee
Create Date: 2025-12-18 18:28:40.746133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f0cac094b6'
down_revision: Union[str, Sequence[str], None] = '79275844a9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_name', sa.String(length=50), nullable=False),
    sa.Column('sent_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_message_logs')
    # ### end Alembic commands ###
